export function guestCopy(lang) {
  const ar = lang === 'ar';
  return {
    gateOpen: ar ? 'افتح الدعوة' : 'Open Invitation',
    gateInvite: ar ? 'يتشرفان بدعوتكم لمشاركتهما أجمل لحظات حياتهما' : 'Joyfully invite you to share in their special day',
    gateScratch: ar ? 'امسح الزهور لتكشف الدعوة' : 'Scratch the flowers to reveal your invitation',
    gateScratchSkip: ar ? 'كشف الدعوة الآن' : 'Reveal it for me',
    countdown: {
      days: ar ? 'يوم' : 'Days',
      hours: ar ? 'ساعة' : 'Hours',
      minutes: ar ? 'دقيقة' : 'Min',
      seconds: ar ? 'ثانية' : 'Sec',
      arrived: ar ? 'اليوم المنتظر وصل ✦' : 'The day has arrived ✦',
    },
    letters: { kicker: ar ? 'رسالة' : 'A Letter', title: ar ? 'كلمات من القلب' : 'Words From The Heart' },
    engagement: { kicker: ar ? 'قصتنا' : 'Our Story', title: ar ? 'فترة الخطوبة' : 'The Engagement' },
    gallery: { kicker: ar ? 'ذكرياتنا' : 'Our Memories', title: ar ? 'معرض الصور' : 'Gallery' },
    outings: { kicker: ar ? 'خرجاتنا' : 'Our Adventures', title: ar ? 'خرجات وفسح' : 'Outings & Trips' },
    timeline: { kicker: ar ? 'برنامج اليوم' : 'The Day', title: ar ? 'الجدول الزمني' : 'Timeline' },
    menu: { kicker: ar ? 'المأدبة' : 'The Feast', title: ar ? 'قائمة الطعام' : 'Menu', defaultCategory: ar ? 'أطباق' : 'Dishes' },
    location: { kicker: ar ? 'المكان' : 'The Venue', title: ar ? 'مكان الحفل' : 'Location', parking: ar ? 'مواقف السيارات' : 'Parking', openMap: ar ? 'افتح الخريطة' : 'Open in Maps' },
    rsvp: {
      kicker: ar ? 'تأكيد الحضور' : 'RSVP',
      title: ar ? 'هل ستحضرون؟' : 'Will You Join Us?',
      namePlaceholder: ar ? 'اسمك بالكامل' : 'Your full name',
      countPlaceholder: ar ? 'عدد الأشخاص' : 'Number of guests',
      attending: ar ? 'بكل سرور' : 'Joyfully Accept',
      notAttending: ar ? 'أعتذر' : 'Regretfully Decline',
      submit: ar ? 'تأكيد' : 'Confirm',
      sending: ar ? 'جاري الإرسال...' : 'Sending...',
      thanks: ar ? 'شكرًا لتأكيدكم، بانتظاركم ✦' : 'Thank you — we can\'t wait to see you ✦',
      error: ar ? 'حصل خطأ، حاول تاني' : 'Something went wrong, please try again',
    },
    comments: {
      kicker: ar ? 'دفتر الضيوف' : 'Guestbook',
      title: ar ? 'اتركوا كلمة' : 'Leave A Wish',
      namePlaceholder: ar ? 'اسمك' : 'Your name',
      textPlaceholder: ar ? 'اكتب رسالتك...' : 'Write your wishes...',
      submit: ar ? 'إرسال' : 'Post',
      sending: ar ? 'جاري الإرسال...' : 'Posting...',
      loading: ar ? 'جاري التحميل...' : 'Loading...',
      empty: ar ? 'لا يوجد تعليقات بعد.' : 'No comments yet.',
      error: ar ? 'حصل خطأ، حاول تاني' : 'Something went wrong, please try again',
      loadMore: ar ? 'عرض المزيد' : 'Show more',
    },
    chat: {
      kicker: ar ? 'تواصل خاص' : 'Private Chat',
      title: ar ? 'راسل العروسين' : 'Message The Couple',
      intro: ar ? 'محادثة خاصة بينك وبين العروسين فقط' : 'A private thread only you and the couple can see',
      namePlaceholder: ar ? 'اسمك' : 'Your name',
      continue: ar ? 'استمرار' : 'Continue',
      loading: ar ? 'جاري التحميل...' : 'Loading...',
      empty: ar ? 'ابعت أول رسالة للعروسين ✦' : 'Send your first message to the couple ✦',
      placeholder: ar ? 'اكتب رسالة...' : 'Type a message...',
      send: ar ? 'إرسال' : 'Send',
    },
  };
}
